### ISSUE TITLE
Pre-configured hdd image not working.

### ISSUE THREAD

**Issue by NewAgeRipper** [xemu-project/xemu-hdd-image#6]
So I fired up Xemu with all the files required. Including the premade pre-configured one. I started a game up and all was fine until it wanted me to make my first save. I was told there wasn't enough space. It's suppose to be an 8 gig pre-configured hdd file. What gives?

**Comment by mborgerson** [comment]
It is an 8G pre-configured build. Can you give more information?
* Confirm you are using the xbox_hdd.qcow2 provided in this repo's release, not someone elses
* Which game did you start?

**Comment by NewAgeRipper** [comment]
> It is an 8G pre-configured build. Can you give more information?
> 
> * Confirm you are using the xbox_hdd.qcow2 provided in this repo's release, not someone elses
> * Which game did you start?

Well, I got the image from the Xemu site first. Figured it was the same as here. 
Game I tried was Taz Wanted since it was small and quick to test.

**Comment by NewAgeRipper** [comment]
> > It is an 8G pre-configured build. Can you give more information?
> > 
> > * Confirm you are using the xbox_hdd.qcow2 provided in this repo's release, not someone elses
> > * Which game did you start?
> 
> Well, I got the image from the Xemu site first. Figured it was the same as here. Game I tried was Taz Wanted since it was small and quick to test.

OK so I got the one from here and all seems fine now. Thanks for answering.
